apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter-config
  namespace: natairankrat-dev
data:
  blackbox.yml: |
    modules:
      https_2xx_insecure:
        prober: http
        timeout: 10s
        http:
          method: GET
          valid_status_codes: []
          tls_config:
            insecure_skip_verify: true
          preferred_ip_protocol: "ip4"
