# infra/k8s/monitoring/postgres-exporter-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-secret
  namespace: natairankrat-dev
type: Opaque
stringData:
  DATA_SOURCE_NAME_MAIN: "postgresql://monitoring:travelallthetime@postgres-main-0.postgres-main:5432/traveldb?sslmode=disable"
  DATA_SOURCE_NAME_HOT: "postgresql://monitoring:travelallthetime@postgres-hot-standby-0.postgres-hot-standby:5432/traveldb?sslmode=disable"