# infra/k8s/postgres/main-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-main-secret
  namespace: natairankrat-dev
type: Opaque
stringData:
  POSTGRES_PASSWORD: "travelallthetime"
  POSTGRES_USER: "appuser"
  POSTGRES_DB: "traveldb"
  REPLICATION_PASSWORD: "butnotforgetabouthome"